steps:
  # clone the repo
  - name: gcr.io/cloud-builders/git
    args:
      - clone
      - https://github.com/kush95300/http-ftp-server-with-go.git
    id: "Clone Repo"
  # build the image
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - 'gcr.io/${_GCP_PROJECT}/${_IMAGE_NAME}:${_IMAGE_VERSION}'
      - .
    id: "build image"

  # push the image to gcr.io
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'gcr.io/${_GCP_PROJECT}/${_IMAGE_NAME}:${_IMAGE_VERSION}'
    id: "push image"

  # deploy the image to cloud run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - services
      #- deploy
      - update
      - ${_SERVICE_NAME}
      - --platform=${_PLATFORM}
      #- --allow-unauthenticated
      - --image=gcr.io/${_GCP_PROJECT}/${_IMAGE_NAME}:${_IMAGE_VERSION}
      - --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=${_COMMIT_SHA},gcb-build-id=${_BUILD_ID},owner=kaushal,gcb-trigger-name=${TRIGGER_NAME},gcb-trigger-id=${_TRIGGER_ID}
      - --region=${_DEPLOY_REGION}
      - --port=80
      - --quiet
    id: "deploy image"
substitutions:
  _GCP_PROJECT: searce-playground-v1

  # IMAGE VARIABLES
  _IMAGE_VERSION: 'v2'
  _IMAGE_NAME: kaushal-server-cloudbuild-cloudrun-cicd

  # Cloud RUN Variable VARIABLES
  _SERVICE_NAME: kush-cicd-automatic
  _DEPLOY_REGION: asia-south1
  _TRIGGER_ID: a0ca31ed-8467-43de-a6bb-4a6887e06328
  _PLATFORM: managed
tags:
  - kaushal-cicd-automatic
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
options:
 logging: CLOUD_LOGGING_ONLY