steps:
  # clone the repo
  - name: gcr.io/cloud-builders/git
    args:
      - clone
      - https://github.com/kush95300/http-ftp-server-with-go.git
  
  # build the image
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - 'gcr.io/${_GCP_PROJECT}/${_IMAGE_NAME}:${_IMAGE_VERSION}'
      - .

  # push the image to gcr.io
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'gcr.io/${_GCP_PROJECT}/${_IMAGE_NAME}:${_IMAGE_VERSION}'
  
  # create a instance
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: 
      - 'compute'
      - 'instances'
      - 'create-with-container'
      - 'kush-vm-name'
      - '--project=${_GCP_PROJECT}'
      - '--network=kaushal-vpc'
      - '--zone=asia-south1-a'
      - '--subnet=kaushal-subnet-1'
      - '--machine-type=e2-micro'
      - '--container-image=gcr.io/${_GCP_PROJECT}/${_IMAGE_NAME}:${_IMAGE_VERSION}'
      - '--tags=kaushal-flask'
      # - '--container-image'
      # - 'gcr.io/${_GCP_PROJECT}/${_IMAGE_NAME}:${_IMAGE_VERSION}'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=asia-south1'
      - 'CLOUDSDK_COMPUTE_ZONE=asia-south1-a'
  
substitutions:
  _IMAGE_VERSION: 'v1.0'
  _GCP_PROJECT: searce-playground-v1
  _IMAGE_NAME: kaushal-server-cloudbuild

options:
 logging: CLOUD_LOGGING_ONLY