steps:
  # clone the repo
  - name: gcr.io/cloud-builders/git
    args:
      - clone
      - https://github.com/kush95300/http-ftp-server-with-go.git
  
  # build the image
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - 'gcr.io/${_GCP_PROJECT}/${_IMAGE_NAME}:${_IMAGE_VERSION}'
      - .

  # push the image to gcr.io
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'gcr.io/${_GCP_PROJECT}/${_IMAGE_NAME}:${_IMAGE_VERSION}'
  
substitutions:
  _GCP_PROJECT: searce-playground-v1

  # IMAGE VARIABLES
  _IMAGE_VERSION: 'v1'
  _IMAGE_NAME: kaushal-server-cloudbuild-cloudrun-cicd

  # Cloud RUN Variable VARIABLES
  # _Service_NAME: kush-vm-name
  # _NETWORK_NAME: kaushal-vpc
  # _SUBNET_NAME: kaushal-subnet-1
  # _INSTANCE_ZONE: asia-south1-a
  # _INSTANCE_MACHINE_TYPE: e2-micro

options:
 logging: CLOUD_LOGGING_ONLY