steps:
  # clone the repo
  - name: gcr.io/cloud-builders/git
    args:
      - clone
      - https://github.com/kush95300/http-ftp-server-with-go.git
  
  # build the image
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - 'gcr.io/${_GCP_PROJECT}/${_IMAGE_NAME}:${_IMAGE_VERSION}'
      - .

  # push the image to gcr.io
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'gcr.io/${_GCP_PROJECT}/${_IMAGE_NAME}:${_IMAGE_VERSION}'
  
  # create a instance
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: 
      - 'compute'
      - 'instances'
      - 'create-with-container'
      - '${_IMAGE_NAME}:${_IMAGE_VERSION}'              # comment it out if you want to use instance name
      #- '${_INSTANCE_NAME}-${_IMAGE_VERSION}'          # uncomment it when use instance name
      - '--project=${_GCP_PROJECT}'
      - '--network=${_NETWORK_NAME}'
      - '--zone=${_INSTANCE_ZONE}'
      - '--subnet=${_SUBNET_NAME}'
      - '--machine-type=${_INSTANCE_MACHINE_TYPE}'
      - '--container-image=gcr.io/${_GCP_PROJECT}/${_IMAGE_NAME}:${_IMAGE_VERSION}'
      - '--tags=allow-all-80'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=asia-south1'
      - 'CLOUDSDK_COMPUTE_ZONE=asia-south1-a'
  
substitutions:
  _GCP_PROJECT: searce-playground-v1

  # IMAGE VARIABLES
  _IMAGE_VERSION: 'v1'
  _IMAGE_NAME: kaushal-server-cloudbuild-cicd-on-vm

  # INSTANCE VARIABLES
  #_INSTANCE_NAME: kush-vm-name
  _NETWORK_NAME: kaushal-vpc
  _SUBNET_NAME: kaushal-subnet-1
  _INSTANCE_ZONE: asia-south1-a
  _INSTANCE_MACHINE_TYPE: e2-micro

options:
 logging: CLOUD_LOGGING_ONLY